name: Build and Optionally Release LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check_version.outputs.version }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Check commit message for version tag
        id: check_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo "::set-output name=version::$VERSION"

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: Main
          root_file: main.tex

      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF-${{ steps.check_version.outputs.version || 'latest' }}
          path: Main/main.pdf

  create_release:
    runs-on: ubuntu-latest
    needs: compile_latex
    if: needs.compile_latex.outputs.version != ''
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: PDF-${{ needs.compile_latex.outputs.version }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.compile_latex.outputs.version }}
          release_name: Release ${{ needs.compile_latex.outputs.version }}
          body: 'Release notes or changelog here'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PDF-${{ needs.compile_latex.outputs.version }}.pdf
          asset_name: main-${{ needs.compile_latex.outputs.version }}.pdf
          asset_content_type: application/pdf
