name: Build and Release LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Cache LaTeX packages
        uses: actions/cache@v2
        with:
          path: ~/.texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Check commit message for version tag
        id: check_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          if [[ "$VERSION" != "" ]]; then
            echo "::set-output name=version::$VERSION"
          fi

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: Main
          root_file: main.tex

      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF-${{ steps.check_version.outputs.version || 'latest' }}
          path: Main/main.pdf

      - name: Create Release
        if: steps.check_version.outputs.version != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check_version.outputs.version }}
          release_name: Release ${{ steps.check_version.outputs.version }}
          body: 'Release notes or changelog here'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: steps.check_version.outputs.version != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Main/main.pdf
          asset_name: main-${{ steps.check_version.outputs.version }}.pdf
          asset_content_type: application/pdf
